# Spigot Configuration File
# 由Yu Minecraft效能最佳化腳本生成 (1.21.8 Compatible)

config-version: 12

settings:
  debug: false
  save-user-cache-on-stop-only: true
  sample-count: 12
  player-shuffle: 0
  user-cache-size: 1000
  int-cache-limit: 1024
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  log-villager-deaths: true
  log-named-deaths: true
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0

messages:
  whitelist: 您不在此伺服器的白名單中！
  unknown-command: 未知指令。輸入 "/help" 查看說明。
  server-full: 伺服器已滿員！
  outdated-client: 過時的客戶端！請使用 {0}
  outdated-server: 過時的伺服器！我正在使用 {0}
  restart: 伺服器正在重啟

commands:
  silent-commandblock-console: false
  log: true
  tab-complete: 0
  send-namespaced: true
  spam-exclusions:
  - /skill

advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled

world-settings:
  default:
    verbose: false
    view-distance: default
    simulation-distance: default
    thunder-chance: 100000
    
    mob-spawn-range: 6
    item-despawn-rate: 6000
    merge-radius:
      item: 2.5
      exp: 3.0
    
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100

    entity-activation-range:
      animals: 24
      monsters: 24
      raiders: 32
      misc: 8
      water: 12
      villagers: 24
      flying-monsters: 24
      
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64

    ticks-per:
      hopper-transfer: 8
      hopper-check: 1

    hopper-amount: 1
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-outpost: 165745296
    seed-endcity: 10387313
    seed-slime: 987234911
    seed-nether: 30084232
    seed-mansion: 10387319
    seed-fossil: 14357921
    seed-portal: 34222645

    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0

    max-tnt-per-tick: 100
    max-tick-time:
      tile: 50
      entity: 50
    
    arrow-despawn-rate: 1200
    trident-despawn-rate: 1200
